sonar.projectKey=arsen-sharifov_uniscept-app
sonar.organization=arsen-sharifov
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests

sonar.exclusions=src/lib/supabase/database.types.ts
sonar.coverage.exclusions=src/**/index.ts,src/lib/interfaces/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
